config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # scope '(:locale)', :locale => /ru|en|fr/ do
  # end

  root 'home#laundry'
  get 'about' => 'home#about'
  get 'location' => 'home#location'
  get 'individuals' => 'home#individuals'
  get 'organizations' => 'home#organizations'
  get 'cleaning' => 'home#dry_cleaning'
  get 'laundry' => 'home#laundry'
  #
  # resource :home, :controller => :home, only: [] do
  #   collection do
  #     get :about
  #     get :location
  #     get :individuals
  #     get :organizations
  #     get :dry_cleaning
  #     get :laundry
  #   end
  # end
  resources :pages, only: [:show]
  resources :posts, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer_review.rb
class CustomerReview < ApplicationRecord
  belongs_to :admin_user
  validates :body, :customer_name, presence: true

  has_attached_file :image
  validates_attachment_content_type :image,
                                     content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/,
                                     message: 'file type is not allowed (only jpeg/png/gif images)'
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :admin_user
  validates :title, :body, presence: true

  has_attached_file :image
  validates_attachment_content_type :image,
                                     content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/,
                                     message: 'file type is not allowed (only jpeg/png/gif images)'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :admin_user
  validates :title, :body, presence: true

  has_attached_file :image
  validates_attachment_content_type :image,
                                     content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/,
                                     message: 'file type is not allowed (only jpeg/png/gif images)'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :set_locale
  #
  # This doesn't work in Safari!
  # def set_locale
  #   I18n.default_locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/[a-z]{2}(?=;)/)
  #   I18n.locale = params[:locale] || I18n.default_locale.first.to_sym
  # end

  def set_admin_locale
    I18n.load_path += Dir[Rails.root.join('config', 'locales', '*.{rb,yml}').to_s]
    I18n.default_locale = :ru
    I18n.reload!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def laundry
    @customer_reviews = CustomerReview.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @posts = pagy(Post.all, items: 2)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<div class="image-header widest-element" style="background-image: url(<%= asset_path 'about/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title">       </div>
    Главная |      
  </div>
</div>
<div>
  <div class="container-fluid wrapper">
    <div class="row flex-column text-box">
      <br />
      <p> Прачечная-химчистка « » - это современное предприятие, оснащенное новейшим европейским оборудованием.
        У нас установлены профессиональные машины шведского производства. ASKO – это гарантия качества мирового бренда.</p>
      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
        Мы предлагаем услуги безопасной, недорогой и качественной чистки и стирки белья и одежды.
      </div>

      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/2icon.svg'%>">
        Технология стирки подразумевает надежную и тщательную водоподготовку, избавляющую используемую воду от загрязняющих
        и вредных примесей. Важным аспектом качества является применение профессиональных моющих средств, в том числе гипо-аллергенных.
      </div>

      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
        Для чистки одежды применяется сухая чистка, деликатная чистка в среде альтернативных органических растворителей, а также аква-чистка.
      </div>

      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/2icon.svg'%>">
        Меховые изделия могут быть очищены как с помощью комплексной чистки, так и ручной БИО чистке деликатными маслами, разработанными
        Новосибирскими учеными для бережного ухода за изделиями из натурального меха.
      </div>

      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
        Спортивная одежда может быть не только очищена, но и озонирована.
      </div>

      <div class="paragraph">
        <img class="paragraph-point" src="<%= asset_path 'common/2icon.svg'%>">
        Выездная бригада позволяет нам осуществлять чистку штор непосредственно у заказчика.
      </div>

      <div class="stickers" style="margin-bottom: 48px;">
        <div class="sticker">
          <img class="sticker-img" src="<%= asset_path 'about/washer.svg'%>">
          <div class="sticker-info">Новейшее европейское оборудование</div>
        </div>
        <div class="sticker">
          <img class="sticker-img" src="<%= asset_path 'about/bleach.svg'%>">
          <div class="sticker-info">Используем только профессиональные <br>средства</div>
        </div>
        <div class="sticker">
          <img class="sticker-img" src="<%= asset_path 'about/employees.svg'%>">
          <div class="sticker-info">Квалифицированные сотрудники</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="map widest-element" style="background-image: url(<%= asset_path 'common/map.png'%>)"></div>
<%= render partial: 'layouts/footer'%>

app/views/home/dry_cleaning.html.erb
<div class="image-header widest-element" style="background-image: url(<%= asset_path 'for_organizations/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title"> Химчистка </div>
    Главная | Химчистка
  </div>
</div>
<div class="container-fluid wrapper">
  <div class="row flex-column text-box for_organizations">
    <div class="paragraph" style="margin-top: 39px;">
      <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
      Чистка изделий это сложный технологический процесс. Конечную стоимость чистки Ваших вещей зависит от типов и количества загрязнений.
      Наш технолог при приемке изделия проконсультирует Вас о видах обработки и стоимости работ.
    </div>
  </div>

  <div class="services">
    <div class="service coat-and-down-jackets clickable-service">
      <div class="service-photo" style="background-image: url(<%= asset_path 'dry_cleaning/foto_1.png'%>); height: 160px;"></div>
      <div style="display:flex; justify-content: center">
        <div class="service-icon-background" style="margin-top: 70px;">
          <img src="<%= asset_path 'dry_cleaning/jacket.svg'%>" >
        </div>
      </div>
      <div class="service-title" style="margin-top: 19px;"> Пальто <br>и пуховики </div>
      <div class="service-price" style="margin-top: 19px;">
        от 800 руб.
      </div>
    </div>

    <div class="service coats-and-jackets clickable-service">
      <div class="service-photo" style="background-image: url(<%= asset_path 'dry_cleaning/foto_2.png'%>); height: 160px;"></div>
      <div style="display:flex; justify-content: center">
        <div class="service-icon-background" style="margin-top: 21.2%;">
          <img src="<%= asset_path 'dry_cleaning/coat.svg'%>" >
        </div>
      </div>
      <div class="service-title" style="margin-top: 19px;"> Плащи <br>и куртки </div>
      <div class="service-price" style="margin-top: 19px;">
        от 550 руб.
      </div>
    </div>

    <div class="service various-materials clickable-service">
      <div class="service-photo" style="background-image: url(<%= asset_path 'dry_cleaning/foto_3.png'%>); height: 160px;"></div>
      <div style="display:flex; justify-content: center">
        <div class="service-icon-background" style="margin-top: 21.2%;">
          <img src="<%= asset_path 'dry_cleaning/cloack.svg'%>" >
        </div>
      </div>
      <div class="service-title" style="margin-top: 19px;"> Изделия <br> из искусственного <br> меха, кожи <br> замаши и велюра </div>
    </div>

    <div class="service genuine-leather-and-fur clickable-service">
      <div class="service-photo" style="background-image: url(<%= asset_path 'dry_cleaning/foto_4.png'%>); height: 160px;"></div>
      <div style="display:flex; justify-content: center">
        <div class="service-icon-background" style="margin-top: 21.2%;">
          <img src="<%= asset_path 'dry_cleaning/cleaning.svg'%>" >
        </div>
      </div>
      <div class="service-title" style="margin-top: 19px;"> Комплексная чистка <br> изделий <br> из натурального <br> меха и кожи </div>
    </div>

    <div class="two-half-sized-services">
      <div class="clickable-service bio-cleaning service-half-sized" style="margin-bottom: 10px;">
        <div class="service-half-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_5.png'%>);"></div>
        <div class="service-half-sized-title"> Био-чистки<br> изделий из <br>натурального <br> меха </div>
      </div>

      <div class="clickable-service jackets-trousers-shirts service-half-sized">
        <div class="service-half-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_6.png'%>);"></div>
        <div class="service-half-sized-title"> Пиджаки<br>жакеты<br>броки<br>рубашки</div>
      </div>
    </div>

    <div class="two-half-sized-services">
      <div class="clickable-service blankets service-half-sized" style="margin-bottom: 10px;">
        <div class="service-half-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_7.png'%>);"></div>
        <div class="service-half-sized-title"> Одеяла<br>и пледы</div>
      </div>

      <div class="clickable-service bedspreads service-half-sized">
        <div class="service-half-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_8.png'%>);"></div>
        <div class="service-half-sized-content">
          <div class="service-half-sized-title" style="margin-left: 0px;"> Покрывала</div>
          <div class="service-half-sized-price">
            от 110 руб./м<sup>2</sup>
          </div>
        </div>
      </div>
    </div>
    <div class="four-quarter-sized-services">
      <div class="clickable-service knitwear service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_9.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Трикотажные <br> изделия
        </div>
      </div>
      <div class="clickable-service evening-dress service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_10.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Вечерняя <br> и шелковая одежда
        </div>
      </div>
      <div class="clickable-service work-clothes service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_15.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Рабочая одежда
        </div>
      </div>
      <div class="clickable-service bags service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_16.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Сумки из натуральной <br> и искусственной кожи, <br>чемоданы
        </div>
      </div>
    </div>

    <div class="four-quarter-sized-services">
      <div class="clickable-service pillows service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_11.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Перьевые подушки
        </div>
      </div>
      <div class="clickable-service interior-items service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_12.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Предметы интерьера:<br> чехлы диванные,<br> портьеры, чехлы<br> на кресла
        </div>
      </div>
    </div>

    <div class="four-quarter-sized-services">
      <div class="clickable-service sports-equipment service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_13.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Спортивная <br> экипировка
        </div>
      </div>
      <div class="clickable-service soft-toys service-quarter-sized">
        <div class="service-quarter-sized-image" style="background-image: url(<%= asset_path 'dry_cleaning/foto_14.png'%>);"></div>
        <div class="service-quarter-sized-title">
          Мягкие игрушки
        </div>
      </div>
    </div>
  </div>
</div>
<div class="map widest-element" style="background-image: url(<%= asset_path 'common/map.png'%>); margin-top: 35px;"></div>

<%= render partial: 'modal_windows/dry_cleaning_modals'%>

<%= render partial: 'layouts/footer'%>

app/views/home/individuals.html.erb
<div class="image-header widest-element" style="background-image: url(<%= asset_path 'for_individuals/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title"> Прачечная для частных лиц </div>
    Главная | Прачечная для частных лиц
  </div>
</div>
<div>
  <div class="container-fluid wrapper">
    <div class="row flex-column text-box">
      <div class="services">
        <div class="service first-service clickable-service" style="cursor: pointer">
          <div class="service-photo" style="background-image: url(<%= asset_path 'for_individuals/foto_1.png'%>)"></div>
          <div style="display:flex; justify-content: center">
            <div class="service-icon-background">
              <img class="service-icon" src="<%= asset_path 'for_individuals/washer.svg'%>" >
            </div>
          </div>
          <div class="service-title"> Стирка и сушка белья </div>
          <div class="service-info"> Стоимость услуги <br> указана за любой вес белья <br> до 5кг.</div>
          <div class="service-price">
            400 руб.
          </div>
        </div>

        <div class="service second-service clickable-service" style="cursor: pointer">
          <div class="service-photo" style="background-image: url(<%= asset_path 'for_individuals/foto_2.png'%>)"></div>
          <div style="display:flex; justify-content: center">
            <div class="service-icon-background">
              <img src="<%= asset_path 'for_individuals/jacket.svg'%>" >
            </div>
          </div>
          <div class="service-title"> Стирка и сушка пуховика </div>
          <div class="service-info"> Стоимость услуги указана за одну <br> вещь. Готовность заказа на <br> следующий день.</div>
          <div class="service-price">
            550 руб.
          </div>
        </div>

        <div class="service third-service clickable-service" style="cursor: pointer">
          <div class="service-photo" style="background-image: url(<%= asset_path 'for_individuals/foto_3.png'%>)"></div>
          <div style="display:flex; justify-content: center">
            <div class="service-icon-background">
              <img class="service-icon" src="<%= asset_path 'for_individuals/towel.svg'%>" >
            </div>
          </div>
          <div class="service-title"> Стирка и сушка одеял,<br>пледов, покрывал</div>
          <div class="service-info"> Цена указана за одну вещь. <br>Готовность заказа на следующий день.</div>
          <div class="service-price">
            550 руб.
          </div>
        </div>
        <div class="service fourth-service clickable-service" style="cursor: pointer">
          <div class="service-photo" style="background-image: url(<%= asset_path 'for_individuals/foto_4.png'%>)"></div>
          <div style="display:flex; justify-content: center">
            <div class="service-icon-background">
              <img class="service-icon" src="<%= asset_path 'for_individuals/linen.svg'%>" >
            </div>
          </div>
          <div class="service-title"> Стирка, сушка и глажка белья</div>
          <div class="service-info"> Стоимость услуги указана за одну <br> вещь, минимальный заказ - шесть <br> вещей.</div>
          <div class="service-price">
            от 40 руб.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="map widest-element" style="background-image: url(<%= asset_path 'common/map.png'%>)"></div>
<%= render partial: 'layouts/footer'%>

<!-- Modal Section -->
<%= render partial: 'modal_windows/first-service'%>
<%= render partial: 'modal_windows/second-service'%>
<%= render partial: 'modal_windows/third-service'%>
<%= render partial: 'modal_windows/fourth-service'%>

app/views/home/location.html.erb
<div class="image-header widest-element" style="background-image: url(<%= asset_path 'location/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title"> Как добраться? </div>
    Главная | Как добраться
  </div>
</div>
<div class="iframe-map-container">
  <iframe src="https://yandex.ru/map-widget/v1/-/CBBDJQds0D" frameborder="0" allowfullscreen="true"></iframe>
</div>
<%= render partial: 'layouts/footer'%>

app/views/home/organizations.html.erb
<div class="image-header widest-element" style="background-image: url(<%= asset_path 'for_organizations/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title"> Прачечная для организаций </div>
    Главная | Прачечная для организаций
  </div>
</div>
<div class="container-fluid wrapper">
  <div class="row flex-column text-box for_organizations">
    <div style="font-family: 'Open Sans'; color:  #303030; font-size: 1.87em; font-weight: 600; margin-top: 38px;">
      Для организаций
    </div>
    <div style="margin-top: 22px;">Прачечная «     » оказывает комплексные услуг и по обслуживанию:</div>

    <div class="stickers">
      <div class="sticker">
        <img class="sticker-img" src="<%= asset_path 'for_organizations/hotel.svg'%>">
        <div class="sticker-info">Санаториев</div>
      </div>
      <div class="sticker">
        <img class="sticker-img" src="<%= asset_path 'for_organizations/tray.svg'%>">
        <div class="sticker-info">Ресторанов<br>и предприятий<br>общественного питания</div>
      </div>
      <div class="sticker">
        <img class="sticker-img" src="<%= asset_path 'for_organizations/room-key.svg'%>">
        <div class="sticker-info">Отелей и гостиниц</div>
      </div>
    </div>

    <div class="paragraph">
      <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
      Собственная транспортная база позволяет нам оперативно забрать у вас белье и вернуть его в чистом и выглаженном виде.
      Соблюдение сроков и своевременная доставка – одно из условий нашей работы.
    </div>

    <div class="paragraph">
      <img class="paragraph-point" src="<%= asset_path 'common/2icon.svg'%>">
      Важнейшим критерием для нас также является сохранность качества и количества белья.
      Мы очень серьезно относимся к соблюдению санитарных норм и правил при стирке белья.
    </div>

    <div class="paragraph" style="margin-bottom: 60px;">
      <img class="paragraph-point" src="<%= asset_path 'common/1icon.svg'%>">
      Заключив договор на долгосрочное обслуживание, вы получаете фиксированные цены на услуг и на все время действия договора.
    </div>
  </div>
</div>
<div class="map widest-element" style="background-image: url(<%= asset_path 'common/map.png'%>)"></div>
<%= render partial: 'layouts/footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Прачечная      </title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content='стирка пуховиков, стирка, чистота, прачечная, белье, сушка, пуховики, химчистка, постельное белье, глажка, глажение, сушка белья, одеяло, покрывало, плед, подушка, мягкие игрушки' />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
       body {
        font-family: 'Open Sans','Source Sans Pro', Helvetica, sans-serif;
       }
    </style>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter51035876 = new Ya.Metrika2({
                        id:51035876,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/51035876" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
  </head>

  <body class="main">
    <div class="container-fluid wrapper">
      <div class="row main-header">
        <a class="logo-header" href="<%= root_path %>">
          <img src="<%= asset_path 'header/logo.svg'%>">
        </a>

        <div class="info-header">
          <img class="t-number-icon" src="<%= asset_path 'header/telephone.svg'%>" />
          <div class="t-number-header">+7 (931) 3-909-123</div>
          <div style="font-family: 'Open Sans';
                      font-size: 1em;
                      display: inline-block;
                      margin-left: 1%;">с 11:00 до 22:00 (без выходных)</div>
          <br>
          <img class="mail-icon-header" src="<%= asset_path 'header/close-envelope.svg'%>" />
          <div style="font-family: 'Open Sans';
                      font-size: 1em;
                      display: inline-block;
                      margin-left: 0.4%;
                      margin-top: 7px;">prachka-laundry@yandex.ru</div>
        </div>

        <div class="messengers-header">
          <a href="/">
            <div class="messenger-icon-header instagram" style="background-image: url(<%= asset_path 'header/instagram.svg' %>)";></div>
          </a>

          <a href="/">
            <div class="messenger-icon-header vk" style="background-image: url(<%= asset_path 'header/vk.svg' %>)";></div>
          </a>

          <a href="/">
            <div class="messenger-icon-header telegram" style="background-image: url(<%= asset_path 'header/telegram.svg' %>)";></div>
          </a>

          <a href="/">
            <div class="messenger-icon-header whatsapp" style="background-image: url(<%= asset_path 'header/whatsapp.svg' %>)";></div>
          </a>

          <a href="/">
            <div class="messenger-icon-header viber" style="background-image: url(<%= asset_path 'header/viber.svg' %>)";></div>
          </a>
        </div>
      </div>
      <div class="row d-flex justify-content-center navigation">
        <a class="navbar-brand navigation-link" href="<%= about_path %>">       </a>
        <a class="link-with-dropdown" href="<%= laundry_path %>">
          <div class="navbar-brand navigation-link has-dropdown" onclick="window.location='<%= laundry_path %>'">
            Прачечная
            <div class="dropdown-links" >
              <a class="dropdown-link" href="<%= individuals_path %>"> Для частных лиц </a>
              <div style="width: 210px; height: 0.5px; color: transparent; margin: auto; box-shadow: 0px -0.3px 0px black;"> </div>
              <a class="dropdown-link" style="margin-top: -0.5px;" href="<%= organizations_path %>"> Для организаций </a>
            </div>
          </div>
        </a>
        <a class="navbar-brand navigation-link" href="<%= cleaning_path %>"> Химчистка </a>
        <a class="navbar-brand navigation-link" href="<%= posts_path %>"> О вашей одежде </a>
        <a class="navbar-brand navigation-link" href="<%= location_path %>"> Как добраться? </a>
        <!-- <% unless Post.all.empty? %>
          <a class="navbar-brand navigation-link" href="<%= posts_path %>"> <%= t(:news_and_discounts) %> </a>
        <% end %>
        <% unless Page.all.empty? %>
          <ul class="navbar-brand navigation-link dropdown-pages"> <%= t(:additionally) %>
            <div class="pages">
              <% Page.all.each do |page| %>
                <a href="<%= page_path(page) %>"><div class="page"> <li> <%= page.title %> </li></div></a>
              <% end %>
            </div>
          </ul>
        <% end %> -->
      </div>
    </div>
      <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<div>
  <div class="row image-header" style="background-image: url(<%= @page.image %>); background-position: center;">
  </div>
  <div class="row flex-column text-box">
    <h2> <%= @page.title %> </h2>
    <br />
    <%= sanitize @page.body %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post-preview">
  <div class="post-preview-image" style="background-image: url(<%= post.image %>);"></div>
  <div class="post-preview-content">
    <div class="post-preview-data">
      <%= post.created_at.strftime("%d.%m.%Y")  %>
    </div>
    <div class="post-preview-title">
      <%= post.title %>
    </div>
     <div class="post-preview-body">
      <%= sanitize post.body %>
    </div>
    <a href="<%= post_path(post) %>">
      <div class="post-preview-button">
        Подробнее
      </div>
    </a>
  </div>
</div>

app/views/posts/show.html.erb
<div class="image-header" style="background-image: url(<%= asset_path 'posts/header.png' %>); background-position: center;">
  <div class="image-header-text">
    <div class="title"> О вашей одежде </div>
    Главная | О вашей одежде
  </div>
</div>
<div class="container-fluid wrapper">
  <div class="row flex-column text-box">
    <div class="post">
      <div class="post-content">
        <div class="post-data">
          <%= @post.created_at.strftime("%d.%m.%Y") %>
        </div>
        <div class="post-title"> <%= @post.title %>

        </div>
        <br>
        <br>
        <br>
        <div class="post-body">
          <%= sanitize @post.body %>
        </div>

        <div class="post-image" style="background-image: url(<%= @post.image %>);"> </div>
      </div>
    </div>

    <a class="post-back-btn" href="<%= posts_path %>">
      Вернуться назад
    </a>
  </div>
</div>
<div class="map widest-element" style="background-image: url(<%= asset_path 'common/map.png'%>)"></div>
<%= render partial: 'layouts/footer'%>